package dev.nyanchuk.toy_factory.model;

public class BadToy extends Toy {

    private String content;

    // Constructor without ID, ID will be generated by ToyController
    public BadToy(String title, String content) {
        super(title, false);  // Pass null for ID, as it will be set by controller
        this.content = content;
    }

    // Getter and setter
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
}
