package dev.nyanchuk.toy_factory.model;

public class GoodToy extends Toy {

    private String brand;
    private int targetAge;
    private String category;

    // Constructor without ID, ID will be generated by ToyController
    public GoodToy(String title, String brand, int targetAge, String category) {
        super(title, true);  // Pass null for ID, as it will be set by controller
        this.brand = brand;
        this.targetAge = targetAge;
        this.category = category;
    }

    // Getters and setters
    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public int getTargetAge() {
        return targetAge;
    }

    public void setTargetAge(int targetAge) {
        this.targetAge = targetAge;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }
}
